### ISSUE TITLE
OnHeartBeat Typo

### ISSUE THREAD

**Issue by Abehuerta** [prooheckcp/RobloxStateMachine#6]
On lines 202 and 206, I believe state.OnHearBeat should be state.OnHeartbeat

https://github.com/prooheckcp/RobloxStateMachine/blob/1bcbf62bc2c2b54dd3e0e51e7682ffd310540e18/src/StateMachine/init.lua#L197-L207

**Comment by ZombieAnomaly** [comment]
Hopeful this pull request will fix this 🤞 
https://github.com/prooheckcp/RobloxStateMachine/pull/7

**Comment by prooheckcp** [comment]
Aware of this issue now, will get this resolved either tonight or tomorrow, thanks for opening it

**Comment by prooheckcp** [comment]
The fix for this is now merged, thank you for reporting it https://github.com/prooheckcp/RobloxStateMachine/pull/8

**Comment by prooheckcp** [comment]
The fix for this is now merged, thank you for reporting it https://github.com/prooheckcp/RobloxStateMachine/pull/8
