### ISSUE TITLE
StateMachine:ChangeData broken?

### ISSUE THREAD

**Issue by Shadercloud** [prooheckcp/RobloxStateMachine#9]
I don't really understand what's going on here:

```
function StateMachine:ChangeData(index: string, newValue: any): ()
    if self._CustomData[index] == newValue then
        return
    end

    self._CustomData[index] = newValue
end
```

Why is it putting the value in `self._CustomData`?  Which is not referenced anywhere else?  Shouldn't it be altering the values in `self.Data` ?

**Comment by prooheckcp** [comment]
That's correct. I remember I was thinking of just straight up completely deprecating :ChangeData and probably made me overlook when rewriting a lot of the code.

I'll fix this today and thank you for keeping me aware of this

**Comment by prooheckcp** [comment]
Should be resolved  now: https://github.com/prooheckcp/RobloxStateMachine/pull/11
